SELECT
  A.value              AS ASSETID,
  C.EM_AM_SOL_ID       AS BCODE,
  D.NAME               AS ASSETTYPE,
  D.DESCRIPTION        AS DESCR,
  B.EM_AM_PRODUCT_CODE AS ASSETSUBTYPE,
  A.DESCRIPTION        AS Detail,
  SUM(ROUND(A.EM_AM_PURCHASE_COST+COALESCE(A.EM_AM_ADDITIONAL_COST,0)-COALESCE(A.EM_AM_CREDIT_TAKEN,0),2)) AS PURCHASECOST,
  A.DATEPURCHASED      AS PURCHASEDATE,
  A.EM_AM_USAGE_DATE   AS USAGEDATE,
  ROUND(100                      /a.annualamortizationpercentage,0)                                        AS USEFULLYEARS,
  CASE
    WHEN EM_AM_USAGE_DATE IS NOT NULL
    THEN EXTRACT( DAY FROM EM_AM_USAGE_DATE)
    ELSE EXTRACT( DAY FROM DATEPURCHASED)
  END AS DAY,
  CASE
    WHEN EM_AM_USAGE_DATE IS NOT NULL
    THEN EXTRACT( MONTH FROM EM_AM_USAGE_DATE)
    ELSE EXTRACT( MONTH FROM DATEPURCHASED)
  END AS MONTH,
  CASE
    WHEN EM_AM_USAGE_DATE IS NOT NULL
    THEN EXTRACT( YEAR FROM EM_AM_USAGE_DATE)
    ELSE EXTRACT( YEAR FROM DATEPURCHASED)
  END AS YEAR
FROM a_asset A
LEFT JOIN
  (SELECT SUM(amortizationamt) AS depreciationFY,
    a_asset_id
  FROM a_amortizationline
  WHERE em_am_dateacct>to_date('31-03-2017','DD-MM-YYYY')
  AND em_am_dateacct  <to_date('01-04-2018','DD-MM-YYYY')
  GROUP BY a_asset_id
  ) Z
ON A.a_asset_id=Z.a_asset_id
LEFT JOIN m_product B
ON A.m_product_id=B.m_product_id
LEFT JOIN AD_org C
ON A.AD_ORG_ID=C.AD_ORG_ID
LEFT JOIN a_asset_group D
ON B.EM_AM_A_ASSET_GROUP_ID=D.A_ASSET_GROUP_ID
LEFT JOIN A_AMORTIZATIONLINE AZL
ON AZL.A_ASSET_ID = A.A_ASSET_ID
LEFT JOIN A_AMORTIZATION AZ
ON AZ.A_AMORTIZATION_ID     = AZL.A_AMORTIZATION_ID
WHERE AZL.em_am_dateacct    =to_date('31-03-2018','DD-MM-YYYY')
AND A.em_am_m_inoutline_id IS NOT NULL
AND A.isactive              ='Y'
AND A.DATEPURCHASED BETWEEN to_date('01-04-2017','DD-MM-YYYY') AND to_date('31-03-2018','DD-MM-YYYY')
AND A.ad_org_id=
  CASE
    WHEN '8D8C4DA4E0EA471C949D2778597638ED' IS NOT NULL
    THEN '8D8C4DA4E0EA471C949D2778597638ED'
    ELSE C.AD_ORG_ID
  END
OR (A.EM_AM_ISTRNDN='Y'
AND A.isactive     ='Y'
AND A.AMORTIZATIONSTARTDATE BETWEEN to_date('01-04-2017','DD-MM-YYYY') AND to_date('31-03-2018','DD-MM-YYYY')
AND A.ad_org_id=
  CASE
    WHEN '8D8C4DA4E0EA471C949D2778597638ED' IS NOT NULL
    THEN '8D8C4DA4E0EA471C949D2778597638ED'
    ELSE C.AD_ORG_ID
  END)
GROUP BY A.A_ASSET_ID,
  C.EM_AM_SOL_ID,
  D.DESCRIPTION,
  B.EM_AM_PRODUCT_CODE,
  D.NAME,
  A.DATEPURCHASED,
  A.AMORTIZATIONSTARTDATE,
  AZ.DATEACCT,
  A.DESCRIPTION,
  A.EM_AM_BOOKVALUE,
  AZL.EM_AM_DATEACCT,
  A.EM_AM_PURCHASE_COST,
  C.name,
  Z.depreciationFY,
  A.value,
  A.ISDISPOSED,
  AZL.AMORTIZATIONAMT,
  A.ANNUALAMORTIZATIONPERCENTAGE,
  A.ISFULLYDEPRECIATED,
  AZL.EM_AM_BOOK_VALUE,
  A.EM_AM_USAGE_DATE;